### ISSUE TITLE
Notifications: "Turn off monitoring of attachment resources in the note [notename]"

### ISSUE THREAD

**Issue by KolyaKorruptis** [rxliuli/joplin-vscode-plugin#30]
Whenever I close any note I get this notification. 
"Turn off monitoring of attachment resources in the note [notename]"

I have set the profile path, restarted vscode, no dice.
What is the plugin expecting me to do here?

**Comment by rxliuli** [comment]
For example, when you open an attachment resource modification in the current note (typically a text file), your modification will be saved and synchronized. When you close the comment, if you modify the attachment resource, it will only be saved locally and not  Synchronization (Note: There are some problems in modifying attachment resources at present, please do not use...)
However, I really should turn it off by default, because under normal circumstances temporarily edited attachment files will be deleted.  .  .

**Comment by victorkane** [comment]
Yes, as someone for whom vscode is practically my main interface to Joplin every day, thanks to this plugin, in one of the upgrades this notice started showing up every time I close any note or todo at all (without attachments). First it disconcerted me, but actually I understand that it is telling me something: before, after closing a file in vscode, one had to go to the Joplin interface and turn off the "eternal editing" state manually after finishing the external editing and saving and closing the file being edited (action which triggers the message always). Now Joplin knows to do this automatically (closing in vscode automatically turns of the "external editing" state in Joplin). So the message is kind of telling me "As far as Joplin is concerned, this note is not being edited any more". Just the wording talks about attachment even if there isn't any.
So as someone who uses this plugin ever day:

1. I should get into the code and send you a pull request, perhaps to add the showing of this message as an option, but I don't have time right now.
2. I'll just put up with the message for now until I do have time :).

**Comment by rxliuli** [comment]
Fixed and released [v0.4.2](https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.4.2), if you have joplin-vscode-plugin installed, it should update automatically
