### ISSUE TITLE
Add support to Quickly open a note using fuzzy search

### ISSUE THREAD

**Issue by 3v1n0** [rxliuli/joplin-vscode-plugin#41]
**Describe the bug**
Feature to quickly open a note from command palette

**To Reproduce**

1. Ctrl + Shift + p
2. Joplin search
3. Start writing
4. Notes are shown only if there's a perfect match

**Expected behavior**
I see that this is using internally the joplin search API, however given that the extension has a list of Joplin notes available, would be nice to have a `Open Note` command that will filter out the notes by name using the native vscode fuzzy search.

**Comment by rxliuli** [comment]
No, this is impossible, because joplin's note list is not loaded all at once, but asynchronously.  In addition, joplin 1.4 updated the search api and added a paging function, pointing out that someone may have a lot of notes, so I can’t load all the notes and implement the search by myself (if you want to optimize the search, you should optimize the search engine of joplin itself)

**Comment by rxliuli** [comment]
There are still some problems with the search engine of joplin, and I may have to deal with it later
https://github.com/laurent22/joplin/issues/4482
https://discourse.joplinapp.org/t/v1-5-4-bug-when-searching-in-chinese-it-does-not-work-as-expected/12888
